CC	:= gcc
CFLAGS	:= -lunicorn -lpthread

all: hole1 hole2 hole3 hole4 \
	hole5 hole6 hole7 hole8 hole9 \
	hole10 hole11 hole12 hole13 hole14 \
	hole15 hole16 hole17 hole18

clean:
	rm hole1 hole2 hole3 hole4 \
	hole5 hole6 hole7 hole8 hole9 \
	hole10 hole11 hole12 hole13 hole14 \
	hole15 hole16 hole17 hole18

hole1: hole1.c hole.c
	$(CC)  -o hole1 hole1.c hole.c $(CFLAGS)

hole2: hole2.c hole.c
	$(CC)  -o hole2 hole2.c hole.c $(CFLAGS)

hole3: hole3.c hole.c
	$(CC)  -o hole3 hole3.c hole.c $(CFLAGS)

hole4: hole4.c hole.c
	$(CC)  -o hole4 hole4.c hole.c $(CFLAGS)

hole5: hole5.c hole.c
	$(CC)  -o hole5 hole5.c hole.c $(CFLAGS)

hole6: hole6.c hole.c
	$(CC)  -o hole6 hole6.c hole.c $(CFLAGS)

hole7: hole7.c hole.c
	$(CC)  -o hole7 hole7.c hole.c $(CFLAGS)

hole8: hole8.c hole.c
	$(CC)  -o hole8 hole8.c hole.c $(CFLAGS)

hole9: hole9.c hole.c
	$(CC)  -o hole9 hole9.c hole.c $(CFLAGS)

hole10: hole10.c hole.c
	$(CC)  -o hole10 hole10.c hole.c $(CFLAGS)

hole11: hole11.c hole.c
	$(CC)  -o hole11 hole11.c hole.c $(CFLAGS)

hole12: hole12.c hole.c
	$(CC)  -o hole12 hole12.c hole.c $(CFLAGS)

hole13: hole13.c hole.c
	$(CC)  -o hole13 hole13.c hole.c $(CFLAGS)

hole14: hole14.c hole.c
	$(CC)  -o hole14 hole14.c hole.c $(CFLAGS)

hole15: hole15.c hole.c
	$(CC)  -o hole15 hole15.c hole.c $(CFLAGS)

hole16: hole16.c hole.c
	$(CC)  -o hole16 hole16.c hole.c $(CFLAGS)

hole17: hole17.c hole.c
	$(CC)  -o hole17 hole17.c hole.c $(CFLAGS)

hole18: hole18.c hole.c
	$(CC)  -o hole18 hole18.c hole.c $(CFLAGS)

