CC	:= gcc
CFLAGS	:= -lpthread -lunicorn

all: hole1 hole2 hole3 hole4 \
	hole5 hole6 hole7 hole8 hole9 \
	hole10 hole11 hole12 hole13 hole14 \
	hole15 hole16 hole17 hole18

clean:
	rm hole1 hole2 hole3 hole4 \
	hole5 hole6 hole7 hole8 hole9 \
	hole10 hole11 hole12 hole13 hole14 \
	hole15 hole16 hole17 hole18

hole1: hole1.c hole.c
	$(CC) $(CFLAGS) -o hole1 hole1.c hole.c

hole2: hole2.c hole.c
	$(CC) $(CFLAGS) -o hole2 hole2.c hole.c

hole3: hole3.c hole.c
	$(CC) $(CFLAGS) -o hole3 hole3.c hole.c

hole4: hole4.c hole.c
	$(CC) $(CFLAGS) -o hole4 hole4.c hole.c

hole5: hole5.c hole.c
	$(CC) $(CFLAGS) -o hole5 hole5.c hole.c

hole6: hole6.c hole.c
	$(CC) $(CFLAGS) -o hole6 hole6.c hole.c

hole7: hole7.c hole.c
	$(CC) $(CFLAGS) -o hole7 hole7.c hole.c

hole8: hole8.c hole.c
	$(CC) $(CFLAGS) -o hole8 hole8.c hole.c

hole9: hole9.c hole.c
	$(CC) $(CFLAGS) -o hole9 hole9.c hole.c

hole10: hole10.c hole.c
	$(CC) $(CFLAGS) -o hole10 hole10.c hole.c

hole11: hole11.c hole.c
	$(CC) $(CFLAGS) -o hole11 hole11.c hole.c

hole12: hole12.c hole.c
	$(CC) $(CFLAGS) -o hole12 hole12.c hole.c

hole13: hole13.c hole.c
	$(CC) $(CFLAGS) -o hole13 hole13.c hole.c

hole14: hole14.c hole.c
	$(CC) $(CFLAGS) -o hole14 hole14.c hole.c

hole15: hole15.c hole.c
	$(CC) $(CFLAGS) -o hole15 hole15.c hole.c

hole16: hole16.c hole.c
	$(CC) $(CFLAGS) -o hole16 hole16.c hole.c

hole17: hole17.c hole.c
	$(CC) $(CFLAGS) -o hole17 hole17.c hole.c

hole18: hole18.c hole.c
	$(CC) $(CFLAGS) -o hole18 hole18.c hole.c


